### ISSUE TITLE
Does the v2m player support seeking?

### ISSUE THREAD

**Issue by mmontag** [jgilje/v2m-player#12]
I'd like to support seek during V2m playback. Does the library support this or is it easy to extend with this behavior? 

I've put in some time with the source, but I'm struggling to understand, especially the workings of `UpdateSampleDelta`. Appreciate the time if someone can help to explain. 

By the way, my project is here. https://github.com/mmontag/chip-player-js
you'll observe a clearly broken seek behavior (among other things) for v2m files :)

**Comment by zvezdochiot** [comment]
@mmontag say:
>I'd like to support seek during V2m playback. Does the library support this or is it easy to extend with this behavior?

I don’t think it will be easy. The code is not "author's". The "author's" code is here: https://github.com/farbrausch/fr_public

@jgilje nly attached sdl to the "author's" code.

**Comment by mmontag** [comment]
@zvezdochiot yeah, I know.  I pinged kb (@kebby) on Twitter and didn't get a response. :) Maybe he'll respond here 😂

**Comment by kebby** [comment]
Hey,

So the answer is yes... ish. V2 is essentially a synthesizer interpreting a MIDI byte stream, and the V2M player feeds it commands from a modified .mid file (with data arranged differently to allow for better compression, and with patch data added).

So the V2M player can seek (check the winamp plugin here https://github.com/farbrausch/fr_public/blob/master/v2/in_v2m/In_v2m.cpp ) but don't expect it to be a perfect sounding seek like with MP3. It'll cut all notes and then start playing from the new position so long notes that you seek right "into" will be missing.

Hope that helps :)

**Comment by jgilje** [comment]
Got it sorted out. The imported code just had a small bug in Play(), which I just pushed a fix for and added a command line option to test it.

@mmontag If you're doing this from a library, seeking is as simple as calling Play(new_time) before resuming your render calls.

**Comment by zvezdochiot** [comment]
@jgilje 
https://github.com/jgilje/v2m-player/blob/a06ff3339c80d34faff9c305a9de74739ae5c6d3/CMakeLists.txt#L9-10
https://github.com/jgilje/v2m-player/blob/a06ff3339c80d34faff9c305a9de74739ae5c6d3/CMakeLists.txt#L15-L22
Version update?

**Comment by jgilje** [comment]
Alright, closing the issue. Thanks @kebby for dropping by and giving a pointer were to look, and I've got to add - love your work in the demo scene :) Too bad there won't be any Revision releases this year.

**Comment by zvezdochiot** [comment]
@mmontag and @jgilje , maybe close issue?

**Comment by kebby** [comment]
Just one thing:

> Too bad there won't be any Revision releases this year.

That's not true :) There won't be a physical Revision this year, but we're taking the whole thing online and do a 72h stream on Twitch, and I can already see the first releases coming into our system. :) http://2020.revision-party.net </shameless-plug>
