### ISSUE TITLE
Amplitude option?

### ISSUE THREAD

**Issue by zvezdochiot** [jgilje/v2m-player#15]
Maybe added Amplitude option?:
```
-a N              amplitude output sound (0..100, default = 50)
```

PS: Open file (for Windows):
https://github.com/jgilje/v2m-player/blob/a4b4ad130fa827d03f4773a3deede788a0c6abf9/src/tinyplayer.cpp#L202
to
```cpp
       file = fopen(v2m_filename, "rb");
```

**Comment by jgilje** [comment]
i'll fix the open binary. have you got a patch ready for the amplitude?

**Comment by zvezdochiot** [comment]
@jgilje say:
>have you got a patch ready for the amplitude?

Not. While I'm chemistry. There are several options. But so far clipping is happening everywhere (Windows). At the same time, the problem is in passing this parameter to the required function. Unfortunately, I didn't find such an opportunity in SDL. There is SDL_MixAudio (https://wiki.libsdl.org/SDL_MixAudio), but I didn't understand how to use it in this case.

**Comment by zvezdochiot** [comment]
Simplest solution: add multiplier 0.0f..1.0f to: 

https://github.com/jgilje/v2m-player/blob/a4b4ad130fa827d03f4773a3deede788a0c6abf9/src/synth_core.cpp#L1016

But that didn't solve my clipping problem.

**Comment by zvezdochiot** [comment]
The problem with cracking under "Window" was solved by replacing: 
https://github.com/jgilje/v2m-player/blob/a4b4ad130fa827d03f4773a3deede788a0c6abf9/src/tinyplayer.cpp#L63
to:
```cpp
    desired.samples = 1024;
```
I have not yet decided how to optimally set the amplitude control. I continue to experiment.

**Comment by jgilje** [comment]
I'm starting to suspect the actual audioformat differs from what's requested, and I never bothered to check this :)

Could you add 
```
    SDL_Log("channels %d, freq %d, samples %d, format %d\n", actual.channels, actual.freq, actual.samples, actual.format);
```
just before `return true` in `init_sdl()`, and let me know the result?

**Comment by zvezdochiot** [comment]
```sh
Now Playing: Dafunk--breeze.v2m
Convert: 329366 b
Strip: 329361 b
INFO: channels 2, freq 44100, samples 1024, format 33056
Length: 180
```
This file is in git: https://github.com/jgilje/v2m-player/blob/master/v2m/Dafunk--breeze.v2mz
```
gzip -cdf Dafunk--breeze.v2mz > Dafunk--breeze.v2m
```

**Comment by jgilje** [comment]
hmmm, got no clue then :) just pushed an updated player with samples == 1024

**Comment by jgilje** [comment]
... and the binary mode has been pushed as well.

**Comment by zvezdochiot** [comment]
>samples == 1024
Not. This is my edit (see https://github.com/jgilje/v2m-player/issues/15#issuecomment-832082059). Without it, I have clicks and crackles at 25 seconds.

**Comment by jgilje** [comment]
@zvezdochiot check the code :) i've updated desired.samples to 1024, as said in the previous comment

**Comment by zvezdochiot** [comment]
> i've updated

Yes, I have seen. This will work. But the question with loudness, I have not solved. I cannot achieve synchronous change of all components. At least bring a new variable into the synthesizer.

**Comment by jgilje** [comment]
is it something like this you're after?

```
static void sdl_callback(void *userdata, Uint8 * stream, int len) {
    player.Render((float*) stream, len / 8);
    float* buf = (float*) stream;
    for (int i = 0; i < (len / 4); ++i) {
        buf[i] *= 1.5f;
    }
}
```

**Comment by zvezdochiot** [comment]
Yes. It's work:
```cpp
static void sdl_callback(void *userdata, Uint8 *stream, int len)
{
    player.Render((float*) stream, len >> 3);
    float* buf = (float*) stream;
    for (int i = 0; i < (len >> 2); ++i) {
        buf[i] *= 0.1f;
    }
}
```
But there will be no problems with passing a parameter to it?

**Comment by jgilje** [comment]
hehe, the clever right shifting will be deducted by the compiler, let's keep the intention clear. closing this issue, will push a remove power-of-two commit afterward.

**Comment by zvezdochiot** [comment]
And about removing `-b`. I only left it as a last resort when I was driving with memory. But now I see that it was a false fear. Isn't it time to delete?
